# Generated by Django 5.2.8 on 2025-12-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_number", models.CharField(max_length=50, unique=True)),
                ("province_full", models.CharField(max_length=100)),
                ("province_short", models.CharField(blank=True, max_length=10)),
                ("car_type", models.CharField(blank=True, max_length=50)),
                ("brand_model", models.CharField(blank=True, max_length=100)),
                ("color_code", models.CharField(default="#007bff", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yp_number", models.PositiveIntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("destination", models.CharField(max_length=255)),
                ("passenger_count", models.PositiveIntegerField(default=1)),
                ("start_mileage", models.PositiveIntegerField()),
                ("end_mileage", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "จองแล้ว"),
                            ("IN_USE", "กำลังใช้งาน"),
                            ("RETURNED", "คืนแล้ว"),
                            ("CANCELLED", "ยกเลิก"),
                        ],
                        default="BOOKED",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "passengers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="passenger_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.car",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="FuelRefill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refill_datetime", models.DateTimeField()),
                ("mileage_before_refill", models.PositiveIntegerField()),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("liter_amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=9)),
                ("station_name", models.CharField(blank=True, max_length=255)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_refills",
                        to="booking.booking",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_refills",
                        to="booking.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("section", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("EMP", "พนักงาน"), ("ADM", "ธุรการ")],
                        default="EMP",
                        max_length=3,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
