# Generated by Django 5.2.8 on 2025-12-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="province_short",
        ),
        migrations.AddField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("DIESEL", "ดีเซล"),
                    ("GAS95", "แก๊สโซฮอล์ 95"),
                    ("GAS91", "แก๊สโซฮอล์ 91"),
                    ("EV", "ไฟฟ้า"),
                    ("OTHER", "อื่น ๆ"),
                ],
                default="DIESEL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="seat_count",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("READY", "พร้อมใช้งาน"),
                    ("MAINTENANCE", "ส่งซ่อม/ซ่อมบำรุง"),
                    ("OUT_OF_SERVICE", "งดใช้งานชั่วคราว"),
                    ("RETIRED", "ยกเลิกใช้งานถาวร"),
                ],
                default="READY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="color_code",
            field=models.CharField(default="#0d6efd", max_length=7),
        ),
    ]
