# Generated by Django 5.2.8 on 2025-12-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_remove_car_province_short_car_fuel_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="brand_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="current_odometer",
            field=models.PositiveIntegerField(
                default=0, help_text="เลขไมล์ล่าสุดของรถคันนี้ (กม.)"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="gear_type",
            field=models.CharField(
                choices=[("AUTO", "อัตโนมัติ"), ("MT", "ธรรมดา")],
                default="AUTO",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="car",
            name="plate_prefix",
            field=models.CharField(
                blank=True, help_text="เช่น งค, ขว, 3ขพ", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("POOL", "รถเช่ากฟฉ.1"),
                    ("OFFICE", "รถประจำกอง/ฝ่าย"),
                    ("INSPECT", "รถตรวจการ/ออกตรวจพื้นที่"),
                    ("OTHER", "อื่น ๆ"),
                ],
                default="POOL",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="color_code",
            field=models.CharField(
                default="#0d6efd", help_text="สีที่ใช้แทนรถคันนี้ในปฏิทิน", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_number",
            field=models.CharField(
                help_text="เช่น 3814, 6247", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="province_full",
            field=models.CharField(
                help_text="เช่น ขอนแก่น, กรุงเทพมหานคร", max_length=100
            ),
        ),
    ]
