# Generated by Django 5.2.8 on 2025-12-04 04:03

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_car_brand_name_car_current_odometer_car_gear_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="end_mileage",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="passenger_count",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="passengers",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_mileage",
        ),
        migrations.RemoveField(
            model_name="car",
            name="brand_model",
        ),
        migrations.RemoveField(
            model_name="car",
            name="car_type",
        ),
        migrations.RemoveField(
            model_name="car",
            name="fuel_type",
        ),
        migrations.RemoveField(
            model_name="car",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="liter_amount",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="mileage_before_refill",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="price_per_liter",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="refill_datetime",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="station_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="section",
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fuelrefill",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelrefill",
            name="liters",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="จำนวนลิตรที่เติม", max_digits=7
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelrefill",
            name="odometer",
            field=models.IntegerField(default=0, help_text="เลขไมล์ ณ ตอนเติม"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fuelrefill",
            name="refill_date",
            field=models.DateField(default=datetime.date(2025, 12, 4)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="booking",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.car",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "จองแล้ว"),
                    ("IN_USE", "กำลังใช้งาน"),
                    ("RETURNED", "คืนแล้ว"),
                    ("CANCELLED", "ยกเลิก"),
                ],
                default="BOOKED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="yp_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="color_code",
            field=models.CharField(default="#377dff", max_length=20),
        ),
        migrations.AlterField(
            model_name="car",
            name="current_odometer",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="car",
            name="gear_type",
            field=models.CharField(
                choices=[("AUTO", "อัตโนมัติ"), ("MANUAL", "ธรรมดา")],
                default="AUTO",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_number",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_prefix",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="car",
            name="province_full",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="car",
            name="seat_count",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="car",
            name="status",
            field=models.CharField(
                choices=[
                    ("READY", "พร้อมใช้งาน"),
                    ("MAINTENANCE", "ส่งซ่อม"),
                    ("OUT_OF_SERVICE", "งดใช้งาน"),
                    ("RETIRED", "ยกเลิกใช้งาน"),
                ],
                default="READY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="usage_type",
            field=models.CharField(
                choices=[
                    ("POOL", "รถเช่ากฟฉ.1"),
                    ("OFFICE", "รถประจำกอง/ฝ่าย"),
                    ("INSPECT", "รถตรวจการ/ออกตรวจพื้นที่"),
                    ("OTHER", "อื่น ๆ"),
                ],
                default="POOL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fuelrefill",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_refills",
                to="booking.booking",
            ),
        ),
        migrations.AlterField(
            model_name="fuelrefill",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, help_text="ราคารวมที่จ่าย", max_digits=9
            ),
        ),
    ]
