# Generated by Django 5.2.8 on 2025-12-04 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_options_remove_booking_end_mileage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="division",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
