# Generated by Django 5.2.8 on 2025-12-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_profile_division"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="co_travelers",
            field=models.ManyToManyField(
                blank=True, related_name="co_travel_bookings", to="booking.profile"
            ),
        ),
    ]
