# Generated by Django 5.2.8 on 2025-12-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_booking_co_travelers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrefill",
            name="odometer_before",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
