# Generated by Django 5.2.8 on 2025-12-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_fuelrefill_odometer_before"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrefill",
            name="odometer_after",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="plate_number",
            field=models.CharField(max_length=10, verbose_name="เลขทะเบียนรถ"),
        ),
    ]
