# Generated by Django 5.2.8 on 2025-12-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_fuelrefill_odometer_after_alter_car_plate_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrefill",
            name="price_per_liter",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="ราคาน้ำมันต่อลิตร",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fuelrefill",
            name="yp_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="เลข ยพ."),
        ),
    ]
