# Generated by Django 5.2.8 on 2025-12-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_fuelrefill_price_per_liter_fuelrefill_yp_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuelrefill",
            name="odometer_after",
        ),
        migrations.RemoveField(
            model_name="fuelrefill",
            name="odometer_before",
        ),
        migrations.AddField(
            model_name="booking",
            name="odometer_after",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="เลขไมล์หลังใช้งาน"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="odometer_before",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="เลขไมล์ก่อนใช้งาน"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="returned_bookings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ผู้ส่งคืนรถ",
            ),
        ),
    ]
