# Generated by Django 5.2.8 on 2025-12-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_remove_fuelrefill_odometer_after_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="yp_number",
            field=models.CharField(
                blank=True, default="", max_length=7, verbose_name="เลข ยพ. (7 หลัก)"
            ),
        ),
    ]
