# Generated by Django 5.2.8 on 2025-12-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_booking_yp_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="yp_number",
        ),
    ]
