# Generated by Django 5.2.8 on 2025-12-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_remove_booking_yp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrefill",
            name="fuel_place",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="สถานที่เติมน้ำมัน"
            ),
        ),
    ]
