# Generated by Django 6.0.1 on 2026-01-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_fuelrefill_fuel_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_status',
            field=models.CharField(choices=[('ACTIVE', 'ปฏิบัติงานอยู่'), ('INACTIVE', 'พ้นสภาพ')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'จองแล้ว'), ('IN_USE', 'กำลังใช้งาน'), ('RETURNED', 'คืนแล้ว'), ('PENDING_RETURN', 'รอคืนรถ'), ('CANCELLED', 'ยกเลิก')], default='BOOKED', max_length=20),
        ),
    ]
